### ISSUE TITLE
Unable to edit tonies on develop commit 223090d

### ISSUE THREAD

**Issue by moviebrain** [toniebox-reverse-engineering/teddycloud#161]
Newest develop branch I was unable to edit tonies in the new /web, would get a failure message. Rolling back to docker compose :latest branch 0.4.5 fixed the issue. Apologies that I lost my record of the errors thrown, but if they aren’t reproducible I can reinstall :develop and retrieve the errors or logs if needed.

**Comment by henryk86** [comment]
It's reproducible:

![image](https://github.com/toniebox-reverse-engineering/teddycloud/assets/166761451/94f147b9-ef54-43ad-9dbb-5142d89655ef)

If I try to edit the tag a second time and choose the same tag it mentions cannot empty source.

Selecting another tag leads to the first error.

But no information in docker logs.

Was not able to find any logs in the container itself.

**Comment by SciLor** [comment]
Thank you for discovering and testing it. Fixed with https://github.com/toniebox-reverse-engineering/teddycloud/commit/e0f460e43c8ea5b0079d74fc1dfc438c555cc0fb

**Comment by henryk86** [comment]
@SciLor Please check the other two functions: set live and set no cloud. They seem to be still broken.
